### ISSUE TITLE
Confuse about multi-decoder feature size

### ISSUE THREAD

**Issue by PaTricksStar** [researchmm/PEN-Net-for-Inpainting#1]
Here equ(5) is rewrited as  phi(L-1) = g(psi(L-1) + g(Phi(L))) where "+"represents channel concat operation .
So phi(L-1) is 4x upsampling of the smallest feature size since there is two 'g' which represent transposed conv.
In the supplement file , L=7 and there is six stride 2 convs. SO phi6 is (h/16, w/16)?
If so ,phi2 is already (h,w) which seems wrong.
Forgive me for my poor description Orz

**Comment by 1900zyh** [comment]
Hi @PaTricksStar 
I'm really sorry for my late response. 
As you mentioned, when L=7, there are six downsample operations (with stride=2)
the size of phi6 should be [h/(2**5), w/(2**5)] = [h/32, w/32]

Finally, thank you for your interest :smile:

**Comment by PaTricksStar** [comment]
If Phi7 is h/64 and phi6 = g(psi6 + g(Phi7)), then phi6 is h/16 since there is two g.
Maybe I miss some details? Check it later.

**Comment by zengyh1900** [comment]
> If Phi7 is h/64 and phi6 = g(psi6 + g(Phi7)), then phi6 is h/16 since there is two g.
> Maybe I miss some details? Check it later.

Oh, I see, you're right. Thank you for your reminder!
 
Eq.5 is confusing, In order to keep the same with Table8 in SUPP, I will update Eq.5 as below, 
![image](https://user-images.githubusercontent.com/7473216/59406084-6e581300-8ddf-11e9-8448-e75153abe388.png)

Is this expression clearer now? 

Thanks,

**Comment by PaTricksStar** [comment]
Yes, that seems reasonable now.
