### ISSUE TITLE
Question in Pyramid L1 losses

### ISSUE THREAD

**Issue by se7enXF** [researchmm/PEN-Net-for-Inpainting#5]
There is no reference in your code about converting Decoder feature map into RGB image and connections in difference level images. I want to implement multi-scale loss, and your work helps me a lot. 
Here is my question: 
1.  Are there connections between difference level images? Such as deconv, upsample.
2. It is easy to learn low level feature map converting into RGB image by 1*1 cnov. But is it working well that hight level feature with high dimension convert into RGB image just by 1*1 cnov?

**Comment by zengyh1900** [comment]
Sorry for my late reply. Here are my ideas:
1. No. We apply multi-scale L1 losses on different levels of images without any connections between them.
2. It's a good question. Actually, we didn't find much improvement or drop of performance by using L1 loss on very high-level features.
