### ISSUE TITLE
hard edges

### ISSUE THREAD

**Issue by niujiaopeng** [researchmm/PEN-Net-for-Inpainting#7]
Thanks for your great job, I found there are hard edges at the border of the mask, how to solve this?

**Comment by zengyh1900** [comment]
Sorry for my late reply. It's a good question. 
We didn't emphasize this common problem in our paper. 
In existing inpainting papers (e.g. Contex-Encoder), the authors usually emphasize larger weight for the loss from hard edges. You can have a try.
